name: ci
on: push
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v5.0.0

      - name: Set up Just command runner
        uses: extractions/setup-just@v3.0.0

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.2

      - name: Check formatting
        run: just format-ci

  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: --deny warnings
    steps:
      - name: Check-out repository
        uses: actions/checkout@v5.0.0

      - name: Set up Just command runner
        uses: extractions/setup-just@v3.0.0

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.2

      - name: Run clippy
        run: just check

  test:
    runs-on: ubuntu-latest
    env:
      # By default output is colorless in CI, enabling color makes test results more readable.
      CARGO_TERM_COLOR: always
    steps:
      - name: Check-out repository
        uses: actions/checkout@v5.0.0

      - name: Set up Just command runner
        uses: extractions/setup-just@v3.0.0

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.2

      - uses: taiki-e/install-action@v2.62.33
        with:
          tool: nextest@0.9.106

      - name: Run tests
        run: just test-all
